/* =========================================================
   Titina Games - Traducciones de los documentos legales
   (Política de Privacidad y Términos y Condiciones)
   Se carga SOLO en privacidad.html y terminos.html.
   Extiende el objeto `translations` definido en i18n.js.
   ========================================================= */
(function () {
    if (typeof translations === 'undefined') return;

    var legal = {
        /* ================= ESPAÑOL ================= */
        es: {
            'priv.title': 'Política de Privacidad',
            'priv.updated': 'Última actualización: 8 de junio de 2026',
            'priv.intro': 'En Titina Games, valoramos tu privacidad. Esta Política de Privacidad explica cómo se recopila, utiliza y divulga la información cuando utilizas nuestros juegos móviles y cualquier otro servicio relacionado.',
            'priv.s1.h': '1. Recopilación de Información',
            'priv.s1.p1': 'Nuestras aplicaciones están diseñadas para no recopilar información de identificación personal directamente de los usuarios. No solicitamos registros de cuentas, nombres, correos electrónicos ni números de teléfono para jugar.',
            'priv.s1.p2': 'Sin embargo, para monetizar y mantener nuestros servicios gratuitos, integramos herramientas de terceros que sí recopilan información técnica de manera automática.',
            'priv.s2.h': '2. Servicios de Terceros (Publicidad y Monetización)',
            'priv.s2.p1': 'Nuestros juegos pueden utilizar Google AdMob para mostrar anuncios. AdMob puede recopilar y procesar información sobre ti de forma automática. Esta información incluye, entre otros:',
            'priv.s2.li1': 'Identificadores únicos de publicidad del dispositivo (como el ID de publicidad de Google o el IDFA de Apple).',
            'priv.s2.li2': 'Datos sobre el dispositivo (fabricante, modelo, sistema operativo, idioma y resolución de pantalla).',
            'priv.s2.li3': 'Datos sobre la interacción con los anuncios (clics, impresiones y visualizaciones).',
            'priv.s2.li4': 'Información de diagnóstico del sistema (informes de fallos o crash logs, rendimiento de la app y uso de memoria).',
            'priv.s2.li5': 'Ubicación aproximada (a nivel de ciudad o país) derivada de la dirección IP.',
            'priv.s2.p2': 'Puedes consultar la política de privacidad de Google relacionada con la publicidad en el siguiente enlace: Políticas y Principios de Publicidad de Google.',
            'priv.s3.h': '3. Uso de la Información',
            'priv.s3.p1': 'La información técnica recopilada automáticamente se utiliza únicamente para:',
            'priv.s3.li1': 'Mostrar anuncios personalizados o no personalizados según corresponda y lo permita tu configuración.',
            'priv.s3.li2': 'Prevenir fraudes y actividades maliciosas dentro del sistema de publicidad.',
            'priv.s3.li3': 'Analizar el rendimiento de las campañas publicitarias.',
            'priv.s3.li4': 'Diagnosticar problemas técnicos, corregir fallos del sistema y optimizar la experiencia de juego.',
            'priv.s4.h': '4. Opciones de Privacidad del Usuario',
            'priv.s4.p1': 'Si deseas limitar la publicidad personalizada en tu dispositivo móvil, puedes ajustar la configuración en tu teléfono:',
            'priv.s4.li1': "<strong>En Android:</strong> Abre Ajustes > Privacidad > Anuncios y selecciona 'Restablecer ID de publicidad' o 'Inhabilitar personalización de anuncios'.",
            'priv.s4.li2': '<strong>En iOS:</strong> Ve a Ajustes > Privacidad > Rastreo y desactiva la opción de permitir que las aplicaciones soliciten rastrearte.',
            'priv.s5.h': '5. Privacidad de los Niños',
            'priv.s5.p1': 'Nuestros juegos no están dirigidos intencionalmente a niños menores de 13 años. No recopilamos conscientemente información personal de niños. Si eres padre o tutor y crees que hemos recopilado información sin tu consentimiento, por favor contáctanos de inmediato.',
            'priv.s6.h': '6. Cambios en esta Política',
            'priv.s6.p1': 'Nos reservamos el derecho de modificar esta Política de Privacidad en cualquier momento. Cualquier cambio será publicado en esta página con la fecha de actualización correspondiente.',
            'priv.s7.h': '7. Contacto',
            'priv.s7.p1': 'Si tienes alguna pregunta sobre esta Política de Privacidad o el tratamiento de tus datos, puedes ponerte en contacto con nosotros a través del correo electrónico:',
            'terms.title': 'Términos y Condiciones de Uso',
            'terms.updated': 'Última actualización: 18 de junio de 2026',
            'terms.intro': 'Al acceder, descargar, instalar o utilizar los videojuegos, sitios web, servidores de comunidad (como Discord) y servicios de <strong>Titina Games</strong>, aceptas cumplir y estar sujeto a estos Términos y Condiciones de Uso. Si no estás de acuerdo con estos términos, por favor no utilices ni accedas a nuestros servicios.',
            'terms.s1.h': '1. Licencia Limitada',
            'terms.s1.p1': 'Titina Games te otorga una licencia personal, limitada, no exclusiva, intransferible, no sublicenciable y revocable para descargar, instalar y utilizar nuestros juegos y servicios únicamente para tu entretenimiento personal y no comercial en dispositivos compatibles de tu propiedad.',
            'terms.s2.h': '2. Propiedad Intelectual',
            'terms.s2.p1': 'Todos los derechos, títulos e intereses relacionados con nuestros juegos y servicios, incluyendo el código fuente, gráficos, diseños, música, efectos de sonido, personajes, diálogos, nombres, logotipos y marcas comerciales, son propiedad exclusiva de Titina Games. La copia, reproducción o distribución no autorizada de cualquiera de nuestros recursos está estrictamente prohibida.',
            'terms.s3.h': '3. Restricciones y Código de Conducta',
            'terms.s3.p1': 'Al utilizar nuestros servicios, aceptas no realizar ni intentar realizar ninguna de las siguientes acciones:',
            'terms.s3.li1': 'Modificar, descompilar, aplicar ingeniería inversa, desensamblar o intentar extraer el código fuente de los juegos o servicios.',
            'terms.s3.li2': 'Utilizar trampas (cheats), bots, hacks, mods o cualquier software de terceros no autorizado para alterar o influir en la experiencia de juego.',
            'terms.s3.li3': 'Utilizar lenguaje ofensivo, abusivo, acosador o inapropiado en nuestros canales oficiales de la comunidad (como Discord) o en los sistemas de nombres del juego.',
            'terms.s4.h': '4. Cuentas de Usuario e Identificador Global',
            'terms.s4.p1': 'En futuras actualizaciones, es posible que puedas crear una cuenta de usuario o utilizar un identificador global para guardar tu progreso en línea. Eres el único responsable de mantener la seguridad y confidencialidad de tus credenciales de inicio de sesión. Titina Games no se hace responsable de ninguna pérdida resultante del acceso no autorizado a tu cuenta.',
            'terms.s5.h': '5. Compras dentro de la Aplicación y Moneda Virtual',
            'terms.s5.p1': 'Nuestros juegos pueden incluir compras dentro de la aplicación utilizando dinero real para adquirir moneda virtual, cosméticos o artículos digitales. Todas las transacciones se procesan de forma segura por la tienda de aplicaciones correspondiente (como Google Play Store o Apple App Store).',
            'terms.s5.p2': 'Todos los artículos y monedas virtuales son licencias digitales intangibles, no tienen valor monetario en el mundo real y no son transferibles ni intercambiables por dinero real. A menos que lo exija la ley local o las políticas de la tienda de aplicaciones, todas las compras son definitivas y no reembolsables.',
            'terms.s6.h': '6. Anuncios y Servicios de Terceros',
            'terms.s6.p1': 'Nuestros juegos gratuitos pueden contener publicidad integrada gestionada a través de Google AdMob u otras plataformas similares. Estos anuncios pueden interactuar con tu dispositivo como se detalla en nuestra Política de Privacidad. Titina Games no respalda y no se hace responsable del contenido, productos o servicios ofrecidos por anunciantes externos.',
            'terms.s7.h': '7. Limitación de Responsabilidad',
            'terms.s7.p1': "Nuestros juegos y servicios se proporcionan 'tal cual' y 'según disponibilidad'. En los modos de juego sin conexión, tu progreso se almacena localmente en tu dispositivo. Titina Games no se hace responsable de la pérdida de progreso, datos o compras si desinstalas la aplicación, borras la memoria caché, formateas tu dispositivo o si tu dispositivo sufre un fallo de hardware.",
            'terms.s8.h': '8. Soporte Técnico y Contacto',
            'terms.s8.p1': 'Para consultas legales, informes de errores, comentarios o solicitudes de soporte técnico, puedes escribirnos directamente a nuestro correo electrónico oficial de atención al cliente:'
        },

        /* ================= ENGLISH ================= */
        en: {
            'priv.title': 'Privacy Policy',
            'priv.updated': 'Last updated: June 8, 2026',
            'priv.intro': 'At Titina Games, we value your privacy. This Privacy Policy explains how information is collected, used and disclosed when you use our mobile games and any other related services.',
            'priv.s1.h': '1. Information We Collect',
            'priv.s1.p1': 'Our applications are designed not to collect personally identifiable information directly from users. We do not require account registration, names, email addresses or phone numbers to play.',
            'priv.s1.p2': 'However, in order to monetize and keep our services free, we integrate third-party tools that do automatically collect technical information.',
            'priv.s2.h': '2. Third-Party Services (Advertising and Monetization)',
            'priv.s2.p1': 'Our games may use Google AdMob to display ads. AdMob may automatically collect and process information about you. This information includes, among others:',
            'priv.s2.li1': "Unique device advertising identifiers (such as the Google Advertising ID or Apple's IDFA).",
            'priv.s2.li2': 'Device data (manufacturer, model, operating system, language and screen resolution).',
            'priv.s2.li3': 'Ad interaction data (clicks, impressions and views).',
            'priv.s2.li4': 'System diagnostic information (crash reports or crash logs, app performance and memory usage).',
            'priv.s2.li5': 'Approximate location (at city or country level) derived from the IP address.',
            'priv.s2.p2': "You can review Google's advertising-related privacy policy at the following link: Google Advertising Policies and Principles.",
            'priv.s3.h': '3. Use of Information',
            'priv.s3.p1': 'The technical information collected automatically is used solely to:',
            'priv.s3.li1': 'Display personalized or non-personalized ads as appropriate and as permitted by your settings.',
            'priv.s3.li2': 'Prevent fraud and malicious activity within the advertising system.',
            'priv.s3.li3': 'Analyze the performance of advertising campaigns.',
            'priv.s3.li4': 'Diagnose technical problems, fix system errors and optimize the gaming experience.',
            'priv.s4.h': '4. User Privacy Options',
            'priv.s4.p1': 'If you wish to limit personalized advertising on your mobile device, you can adjust the settings on your phone:',
            'priv.s4.li1': "<strong>On Android:</strong> Open Settings > Privacy > Ads and select 'Reset advertising ID' or 'Opt out of Ads Personalization'.",
            'priv.s4.li2': '<strong>On iOS:</strong> Go to Settings > Privacy > Tracking and turn off the option that allows apps to request to track you.',
            'priv.s5.h': "5. Children's Privacy",
            'priv.s5.p1': 'Our games are not intentionally directed at children under 13 years of age. We do not knowingly collect personal information from children. If you are a parent or guardian and believe we have collected information without your consent, please contact us immediately.',
            'priv.s6.h': '6. Changes to This Policy',
            'priv.s6.p1': 'We reserve the right to modify this Privacy Policy at any time. Any changes will be posted on this page with the corresponding update date.',
            'priv.s7.h': '7. Contact',
            'priv.s7.p1': 'If you have any questions about this Privacy Policy or the handling of your data, you can contact us via email:',
            'terms.title': 'Terms and Conditions of Use',
            'terms.updated': 'Last updated: June 18, 2026',
            'terms.intro': 'By accessing, downloading, installing or using the video games, websites, community servers (such as Discord) and services of <strong>Titina Games</strong>, you agree to comply with and be bound by these Terms and Conditions of Use. If you do not agree to these terms, please do not use or access our services.',
            'terms.s1.h': '1. Limited License',
            'terms.s1.p1': 'Titina Games grants you a personal, limited, non-exclusive, non-transferable, non-sublicensable and revocable license to download, install and use our games and services solely for your personal, non-commercial entertainment on compatible devices that you own.',
            'terms.s2.h': '2. Intellectual Property',
            'terms.s2.p1': 'All rights, title and interest related to our games and services, including source code, graphics, designs, music, sound effects, characters, dialogue, names, logos and trademarks, are the exclusive property of Titina Games. The unauthorized copying, reproduction or distribution of any of our resources is strictly prohibited.',
            'terms.s3.h': '3. Restrictions and Code of Conduct',
            'terms.s3.p1': 'By using our services, you agree not to perform or attempt to perform any of the following actions:',
            'terms.s3.li1': 'Modify, decompile, reverse engineer, disassemble or attempt to extract the source code of the games or services.',
            'terms.s3.li2': 'Use cheats, bots, hacks, mods or any unauthorized third-party software to alter or influence the gaming experience.',
            'terms.s3.li3': "Use offensive, abusive, harassing or inappropriate language in our official community channels (such as Discord) or in the game's naming systems.",
            'terms.s4.h': '4. User Accounts and Global Identifier',
            'terms.s4.p1': 'In future updates, you may be able to create a user account or use a global identifier to save your progress online. You are solely responsible for maintaining the security and confidentiality of your login credentials. Titina Games is not responsible for any loss resulting from unauthorized access to your account.',
            'terms.s5.h': '5. In-App Purchases and Virtual Currency',
            'terms.s5.p1': 'Our games may include in-app purchases using real money to acquire virtual currency, cosmetics or digital items. All transactions are processed securely by the corresponding app store (such as Google Play Store or Apple App Store).',
            'terms.s5.p2': 'All virtual items and currencies are intangible digital licenses, have no monetary value in the real world and are not transferable or exchangeable for real money. Unless required by local law or app store policies, all purchases are final and non-refundable.',
            'terms.s6.h': '6. Advertising and Third-Party Services',
            'terms.s6.p1': 'Our free games may contain integrated advertising managed through Google AdMob or other similar platforms. These ads may interact with your device as detailed in our Privacy Policy. Titina Games does not endorse and is not responsible for the content, products or services offered by external advertisers.',
            'terms.s7.h': '7. Limitation of Liability',
            'terms.s7.p1': "Our games and services are provided 'as is' and 'as available'. In offline game modes, your progress is stored locally on your device. Titina Games is not responsible for the loss of progress, data or purchases if you uninstall the app, clear the cache, format your device or if your device suffers a hardware failure.",
            'terms.s8.h': '8. Technical Support and Contact',
            'terms.s8.p1': 'For legal inquiries, bug reports, feedback or technical support requests, you can write to us directly at our official customer service email:'
        },

        /* ================= PORTUGUÊS ================= */
        pt: {
            'priv.title': 'Política de Privacidade',
            'priv.updated': 'Última atualização: 8 de junho de 2026',
            'priv.intro': 'Na Titina Games, valorizamos a sua privacidade. Esta Política de Privacidade explica como as informações são coletadas, usadas e divulgadas quando você utiliza nossos jogos para celular e qualquer outro serviço relacionado.',
            'priv.s1.h': '1. Coleta de Informações',
            'priv.s1.p1': 'Nossos aplicativos são projetados para não coletar informações de identificação pessoal diretamente dos usuários. Não solicitamos registro de contas, nomes, e-mails nem números de telefone para jogar.',
            'priv.s1.p2': 'No entanto, para monetizar e manter nossos serviços gratuitos, integramos ferramentas de terceiros que coletam informações técnicas de forma automática.',
            'priv.s2.h': '2. Serviços de Terceiros (Publicidade e Monetização)',
            'priv.s2.p1': 'Nossos jogos podem utilizar o Google AdMob para exibir anúncios. O AdMob pode coletar e processar informações sobre você de forma automática. Essas informações incluem, entre outras:',
            'priv.s2.li1': 'Identificadores únicos de publicidade do dispositivo (como o ID de publicidade do Google ou o IDFA da Apple).',
            'priv.s2.li2': 'Dados sobre o dispositivo (fabricante, modelo, sistema operacional, idioma e resolução de tela).',
            'priv.s2.li3': 'Dados sobre a interação com os anúncios (cliques, impressões e visualizações).',
            'priv.s2.li4': 'Informações de diagnóstico do sistema (relatórios de falhas ou crash logs, desempenho do app e uso de memória).',
            'priv.s2.li5': 'Localização aproximada (a nível de cidade ou país) derivada do endereço IP.',
            'priv.s2.p2': 'Você pode consultar a política de privacidade do Google relacionada à publicidade no seguinte link: Políticas e Princípios de Publicidade do Google.',
            'priv.s3.h': '3. Uso das Informações',
            'priv.s3.p1': 'As informações técnicas coletadas automaticamente são utilizadas exclusivamente para:',
            'priv.s3.li1': 'Exibir anúncios personalizados ou não personalizados, conforme apropriado e permitido pelas suas configurações.',
            'priv.s3.li2': 'Prevenir fraudes e atividades maliciosas dentro do sistema de publicidade.',
            'priv.s3.li3': 'Analisar o desempenho das campanhas publicitárias.',
            'priv.s3.li4': 'Diagnosticar problemas técnicos, corrigir falhas do sistema e otimizar a experiência de jogo.',
            'priv.s4.h': '4. Opções de Privacidade do Usuário',
            'priv.s4.p1': 'Se você deseja limitar a publicidade personalizada no seu dispositivo móvel, pode ajustar as configurações no seu telefone:',
            'priv.s4.li1': "<strong>No Android:</strong> Abra Configurações > Privacidade > Anúncios e selecione 'Redefinir ID de publicidade' ou 'Desativar personalização de anúncios'.",
            'priv.s4.li2': '<strong>No iOS:</strong> Vá em Ajustes > Privacidade > Rastreamento e desative a opção de permitir que os aplicativos solicitem rastrear você.',
            'priv.s5.h': '5. Privacidade das Crianças',
            'priv.s5.p1': 'Nossos jogos não são intencionalmente direcionados a crianças menores de 13 anos. Não coletamos conscientemente informações pessoais de crianças. Se você é pai, mãe ou responsável e acredita que coletamos informações sem o seu consentimento, entre em contato conosco imediatamente.',
            'priv.s6.h': '6. Alterações nesta Política',
            'priv.s6.p1': 'Reservamo-nos o direito de modificar esta Política de Privacidade a qualquer momento. Qualquer alteração será publicada nesta página com a respectiva data de atualização.',
            'priv.s7.h': '7. Contato',
            'priv.s7.p1': 'Se você tiver alguma dúvida sobre esta Política de Privacidade ou sobre o tratamento dos seus dados, pode entrar em contato conosco pelo e-mail:',
            'terms.title': 'Termos e Condições de Uso',
            'terms.updated': 'Última atualização: 18 de junho de 2026',
            'terms.intro': 'Ao acessar, baixar, instalar ou utilizar os videojogos, sites, servidores de comunidade (como o Discord) e serviços da <strong>Titina Games</strong>, você concorda em cumprir e se sujeitar a estes Termos e Condições de Uso. Se você não concorda com estes termos, por favor não utilize nem acesse nossos serviços.',
            'terms.s1.h': '1. Licença Limitada',
            'terms.s1.p1': 'A Titina Games concede a você uma licença pessoal, limitada, não exclusiva, intransferível, não sublicenciável e revogável para baixar, instalar e utilizar nossos jogos e serviços unicamente para o seu entretenimento pessoal e não comercial em dispositivos compatíveis de sua propriedade.',
            'terms.s2.h': '2. Propriedade Intelectual',
            'terms.s2.p1': 'Todos os direitos, títulos e interesses relacionados aos nossos jogos e serviços, incluindo o código-fonte, gráficos, designs, música, efeitos sonoros, personagens, diálogos, nomes, logotipos e marcas registradas, são propriedade exclusiva da Titina Games. A cópia, reprodução ou distribuição não autorizada de qualquer um dos nossos recursos é estritamente proibida.',
            'terms.s3.h': '3. Restrições e Código de Conduta',
            'terms.s3.p1': 'Ao utilizar nossos serviços, você concorda em não realizar nem tentar realizar nenhuma das seguintes ações:',
            'terms.s3.li1': 'Modificar, descompilar, aplicar engenharia reversa, desmontar ou tentar extrair o código-fonte dos jogos ou serviços.',
            'terms.s3.li2': 'Utilizar trapaças (cheats), bots, hacks, mods ou qualquer software de terceiros não autorizado para alterar ou influenciar a experiência de jogo.',
            'terms.s3.li3': 'Utilizar linguagem ofensiva, abusiva, de assédio ou inapropriada em nossos canais oficiais da comunidade (como o Discord) ou nos sistemas de nomes do jogo.',
            'terms.s4.h': '4. Contas de Usuário e Identificador Global',
            'terms.s4.p1': 'Em atualizações futuras, é possível que você possa criar uma conta de usuário ou utilizar um identificador global para salvar seu progresso online. Você é o único responsável por manter a segurança e a confidencialidade das suas credenciais de acesso. A Titina Games não se responsabiliza por qualquer perda resultante do acesso não autorizado à sua conta.',
            'terms.s5.h': '5. Compras no Aplicativo e Moeda Virtual',
            'terms.s5.p1': 'Nossos jogos podem incluir compras no aplicativo utilizando dinheiro real para adquirir moeda virtual, cosméticos ou itens digitais. Todas as transações são processadas de forma segura pela loja de aplicativos correspondente (como a Google Play Store ou a Apple App Store).',
            'terms.s5.p2': 'Todos os itens e moedas virtuais são licenças digitais intangíveis, não têm valor monetário no mundo real e não são transferíveis nem trocáveis por dinheiro real. A menos que exigido pela lei local ou pelas políticas da loja de aplicativos, todas as compras são definitivas e não reembolsáveis.',
            'terms.s6.h': '6. Anúncios e Serviços de Terceiros',
            'terms.s6.p1': 'Nossos jogos gratuitos podem conter publicidade integrada gerenciada através do Google AdMob ou de outras plataformas semelhantes. Esses anúncios podem interagir com o seu dispositivo conforme detalhado em nossa Política de Privacidade. A Titina Games não endossa e não se responsabiliza pelo conteúdo, produtos ou serviços oferecidos por anunciantes externos.',
            'terms.s7.h': '7. Limitação de Responsabilidade',
            'terms.s7.p1': "Nossos jogos e serviços são fornecidos 'no estado em que se encontram' e 'conforme a disponibilidade'. Nos modos de jogo offline, seu progresso é armazenado localmente no seu dispositivo. A Titina Games não se responsabiliza pela perda de progresso, dados ou compras caso você desinstale o aplicativo, limpe o cache, formate o dispositivo ou se o seu dispositivo sofrer uma falha de hardware.",
            'terms.s8.h': '8. Suporte Técnico e Contato',
            'terms.s8.p1': 'Para consultas jurídicas, relatos de erros, comentários ou solicitações de suporte técnico, você pode escrever diretamente para o nosso e-mail oficial de atendimento ao cliente:'
        },

        /* ================= BAHASA INDONESIA ================= */
        id: {
            'priv.title': 'Kebijakan Privasi',
            'priv.updated': 'Terakhir diperbarui: 8 Juni 2026',
            'priv.intro': 'Di Titina Games, kami menghargai privasi Anda. Kebijakan Privasi ini menjelaskan bagaimana informasi dikumpulkan, digunakan, dan diungkapkan saat Anda menggunakan game seluler kami dan layanan terkait lainnya.',
            'priv.s1.h': '1. Pengumpulan Informasi',
            'priv.s1.p1': 'Aplikasi kami dirancang untuk tidak mengumpulkan informasi identitas pribadi secara langsung dari pengguna. Kami tidak meminta pendaftaran akun, nama, alamat email, maupun nomor telepon untuk bermain.',
            'priv.s1.p2': 'Namun, untuk memonetisasi dan menjaga layanan kami tetap gratis, kami mengintegrasikan alat pihak ketiga yang mengumpulkan informasi teknis secara otomatis.',
            'priv.s2.h': '2. Layanan Pihak Ketiga (Iklan dan Monetisasi)',
            'priv.s2.p1': 'Game kami dapat menggunakan Google AdMob untuk menampilkan iklan. AdMob dapat mengumpulkan dan memproses informasi tentang Anda secara otomatis. Informasi ini meliputi, antara lain:',
            'priv.s2.li1': 'Pengenal iklan unik perangkat (seperti ID Iklan Google atau IDFA Apple).',
            'priv.s2.li2': 'Data tentang perangkat (produsen, model, sistem operasi, bahasa, dan resolusi layar).',
            'priv.s2.li3': 'Data tentang interaksi dengan iklan (klik, tayangan, dan penayangan).',
            'priv.s2.li4': 'Informasi diagnostik sistem (laporan kerusakan atau crash log, performa aplikasi, dan penggunaan memori).',
            'priv.s2.li5': 'Perkiraan lokasi (tingkat kota atau negara) yang berasal dari alamat IP.',
            'priv.s2.p2': 'Anda dapat membaca kebijakan privasi Google terkait periklanan melalui tautan berikut: Kebijakan dan Prinsip Periklanan Google.',
            'priv.s3.h': '3. Penggunaan Informasi',
            'priv.s3.p1': 'Informasi teknis yang dikumpulkan secara otomatis hanya digunakan untuk:',
            'priv.s3.li1': 'Menampilkan iklan yang dipersonalisasi atau tidak dipersonalisasi sesuai kebutuhan dan sesuai izin pengaturan Anda.',
            'priv.s3.li2': 'Mencegah penipuan dan aktivitas berbahaya di dalam sistem periklanan.',
            'priv.s3.li3': 'Menganalisis performa kampanye iklan.',
            'priv.s3.li4': 'Mendiagnosis masalah teknis, memperbaiki kesalahan sistem, dan mengoptimalkan pengalaman bermain.',
            'priv.s4.h': '4. Opsi Privasi Pengguna',
            'priv.s4.p1': 'Jika Anda ingin membatasi iklan yang dipersonalisasi di perangkat seluler Anda, Anda dapat menyesuaikan pengaturan di ponsel Anda:',
            'priv.s4.li1': "<strong>Di Android:</strong> Buka Setelan > Privasi > Iklan lalu pilih 'Setel ulang ID iklan' atau 'Nonaktifkan personalisasi iklan'.",
            'priv.s4.li2': '<strong>Di iOS:</strong> Buka Pengaturan > Privasi > Pelacakan dan matikan opsi yang mengizinkan aplikasi meminta melacak Anda.',
            'priv.s5.h': '5. Privasi Anak-Anak',
            'priv.s5.p1': 'Game kami tidak ditujukan secara sengaja untuk anak-anak di bawah usia 13 tahun. Kami tidak dengan sengaja mengumpulkan informasi pribadi dari anak-anak. Jika Anda orang tua atau wali dan yakin bahwa kami telah mengumpulkan informasi tanpa persetujuan Anda, silakan segera hubungi kami.',
            'priv.s6.h': '6. Perubahan pada Kebijakan Ini',
            'priv.s6.p1': 'Kami berhak mengubah Kebijakan Privasi ini kapan saja. Setiap perubahan akan dipublikasikan di halaman ini beserta tanggal pembaruan yang sesuai.',
            'priv.s7.h': '7. Kontak',
            'priv.s7.p1': 'Jika Anda memiliki pertanyaan tentang Kebijakan Privasi ini atau tentang penanganan data Anda, Anda dapat menghubungi kami melalui email:',
            'terms.title': 'Syarat dan Ketentuan Penggunaan',
            'terms.updated': 'Terakhir diperbarui: 18 Juni 2026',
            'terms.intro': 'Dengan mengakses, mengunduh, memasang, atau menggunakan video game, situs web, server komunitas (seperti Discord), dan layanan dari <strong>Titina Games</strong>, Anda setuju untuk mematuhi dan terikat pada Syarat dan Ketentuan Penggunaan ini. Jika Anda tidak menyetujui ketentuan ini, mohon jangan menggunakan atau mengakses layanan kami.',
            'terms.s1.h': '1. Lisensi Terbatas',
            'terms.s1.p1': 'Titina Games memberi Anda lisensi pribadi, terbatas, non-eksklusif, tidak dapat dipindahtangankan, tidak dapat disublisensikan, dan dapat dicabut untuk mengunduh, memasang, dan menggunakan game serta layanan kami hanya untuk hiburan pribadi dan non-komersial di perangkat kompatibel milik Anda.',
            'terms.s2.h': '2. Kekayaan Intelektual',
            'terms.s2.p1': 'Semua hak, kepemilikan, dan kepentingan yang terkait dengan game dan layanan kami, termasuk kode sumber, grafik, desain, musik, efek suara, karakter, dialog, nama, logo, dan merek dagang, merupakan milik eksklusif Titina Games. Penyalinan, reproduksi, atau distribusi tanpa izin atas sumber daya kami dilarang keras.',
            'terms.s3.h': '3. Pembatasan dan Kode Etik',
            'terms.s3.p1': 'Dengan menggunakan layanan kami, Anda setuju untuk tidak melakukan atau mencoba melakukan tindakan berikut:',
            'terms.s3.li1': 'Memodifikasi, mendekompilasi, merekayasa balik, membongkar, atau mencoba mengekstrak kode sumber dari game atau layanan.',
            'terms.s3.li2': 'Menggunakan cheat, bot, hack, mod, atau perangkat lunak pihak ketiga tanpa izin untuk mengubah atau memengaruhi pengalaman bermain.',
            'terms.s3.li3': 'Menggunakan bahasa yang ofensif, kasar, melecehkan, atau tidak pantas di saluran komunitas resmi kami (seperti Discord) atau dalam sistem penamaan game.',
            'terms.s4.h': '4. Akun Pengguna dan Pengenal Global',
            'terms.s4.p1': 'Pada pembaruan mendatang, Anda mungkin dapat membuat akun pengguna atau menggunakan pengenal global untuk menyimpan progres Anda secara online. Anda sepenuhnya bertanggung jawab untuk menjaga keamanan dan kerahasiaan kredensial login Anda. Titina Games tidak bertanggung jawab atas kerugian apa pun yang timbul akibat akses tidak sah ke akun Anda.',
            'terms.s5.h': '5. Pembelian Dalam Aplikasi dan Mata Uang Virtual',
            'terms.s5.p1': 'Game kami dapat mencakup pembelian dalam aplikasi menggunakan uang sungguhan untuk memperoleh mata uang virtual, item kosmetik, atau barang digital. Semua transaksi diproses secara aman oleh toko aplikasi terkait (seperti Google Play Store atau Apple App Store).',
            'terms.s5.p2': 'Semua item dan mata uang virtual adalah lisensi digital yang tidak berwujud, tidak memiliki nilai moneter di dunia nyata, dan tidak dapat dipindahtangankan maupun ditukar dengan uang sungguhan. Kecuali diwajibkan oleh hukum setempat atau kebijakan toko aplikasi, semua pembelian bersifat final dan tidak dapat dikembalikan.',
            'terms.s6.h': '6. Iklan dan Layanan Pihak Ketiga',
            'terms.s6.p1': 'Game gratis kami dapat memuat iklan terintegrasi yang dikelola melalui Google AdMob atau platform serupa lainnya. Iklan ini dapat berinteraksi dengan perangkat Anda sebagaimana dijelaskan dalam Kebijakan Privasi kami. Titina Games tidak mendukung dan tidak bertanggung jawab atas konten, produk, atau layanan yang ditawarkan oleh pengiklan eksternal.',
            'terms.s7.h': '7. Batasan Tanggung Jawab',
            'terms.s7.p1': "Game dan layanan kami disediakan 'sebagaimana adanya' dan 'sesuai ketersediaan'. Dalam mode permainan offline, progres Anda disimpan secara lokal di perangkat Anda. Titina Games tidak bertanggung jawab atas hilangnya progres, data, atau pembelian jika Anda menghapus aplikasi, membersihkan cache, memformat perangkat, atau jika perangkat Anda mengalami kegagalan perangkat keras.",
            'terms.s8.h': '8. Dukungan Teknis dan Kontak',
            'terms.s8.p1': 'Untuk pertanyaan hukum, laporan bug, masukan, atau permintaan dukungan teknis, Anda dapat menulis langsung ke email layanan pelanggan resmi kami:'
        },

        /* ================= ไทย (Thai) ================= */
        th: {
            'priv.title': 'นโยบายความเป็นส่วนตัว',
            'priv.updated': 'อัปเดตล่าสุด: 8 มิถุนายน 2026',
            'priv.intro': 'ที่ Titina Games เราให้ความสำคัญกับความเป็นส่วนตัวของคุณ นโยบายความเป็นส่วนตัวนี้อธิบายว่าเรารวบรวม ใช้ และเปิดเผยข้อมูลอย่างไรเมื่อคุณใช้เกมมือถือของเราและบริการอื่น ๆ ที่เกี่ยวข้อง',
            'priv.s1.h': '1. การเก็บรวบรวมข้อมูล',
            'priv.s1.p1': 'แอปพลิเคชันของเราออกแบบมาเพื่อไม่เก็บข้อมูลที่ระบุตัวตนส่วนบุคคลโดยตรงจากผู้ใช้ เราไม่ขอให้ลงทะเบียนบัญชี ชื่อ อีเมล หรือหมายเลขโทรศัพท์เพื่อเล่นเกม',
            'priv.s1.p2': 'อย่างไรก็ตาม เพื่อสร้างรายได้และรักษาบริการของเราให้ฟรี เราได้รวมเครื่องมือของบุคคลที่สามซึ่งเก็บรวบรวมข้อมูลทางเทคนิคโดยอัตโนมัติ',
            'priv.s2.h': '2. บริการของบุคคลที่สาม (โฆษณาและการสร้างรายได้)',
            'priv.s2.p1': 'เกมของเราอาจใช้ Google AdMob เพื่อแสดงโฆษณา AdMob อาจเก็บรวบรวมและประมวลผลข้อมูลเกี่ยวกับคุณโดยอัตโนมัติ ข้อมูลนี้รวมถึงแต่ไม่จำกัดเพียง:',
            'priv.s2.li1': 'ตัวระบุโฆษณาเฉพาะของอุปกรณ์ (เช่น รหัสโฆษณาของ Google หรือ IDFA ของ Apple)',
            'priv.s2.li2': 'ข้อมูลเกี่ยวกับอุปกรณ์ (ผู้ผลิต รุ่น ระบบปฏิบัติการ ภาษา และความละเอียดหน้าจอ)',
            'priv.s2.li3': 'ข้อมูลเกี่ยวกับการโต้ตอบกับโฆษณา (การคลิก การแสดงผล และการรับชม)',
            'priv.s2.li4': 'ข้อมูลการวินิจฉัยระบบ (รายงานข้อขัดข้องหรือ crash log ประสิทธิภาพของแอป และการใช้หน่วยความจำ)',
            'priv.s2.li5': 'ตำแหน่งโดยประมาณ (ระดับเมืองหรือประเทศ) ที่ได้จากที่อยู่ IP',
            'priv.s2.p2': 'คุณสามารถอ่านนโยบายความเป็นส่วนตัวของ Google ที่เกี่ยวข้องกับโฆษณาได้ที่ลิงก์ต่อไปนี้: นโยบายและหลักการโฆษณาของ Google',
            'priv.s3.h': '3. การใช้ข้อมูล',
            'priv.s3.p1': 'ข้อมูลทางเทคนิคที่เก็บรวบรวมโดยอัตโนมัติจะถูกใช้เพื่อ:',
            'priv.s3.li1': 'แสดงโฆษณาแบบเฉพาะบุคคลหรือแบบไม่เฉพาะบุคคลตามความเหมาะสมและตามที่การตั้งค่าของคุณอนุญาต',
            'priv.s3.li2': 'ป้องกันการฉ้อโกงและกิจกรรมที่เป็นอันตรายภายในระบบโฆษณา',
            'priv.s3.li3': 'วิเคราะห์ประสิทธิภาพของแคมเปญโฆษณา',
            'priv.s3.li4': 'วินิจฉัยปัญหาทางเทคนิค แก้ไขข้อผิดพลาดของระบบ และเพิ่มประสิทธิภาพประสบการณ์การเล่น',
            'priv.s4.h': '4. ตัวเลือกความเป็นส่วนตัวของผู้ใช้',
            'priv.s4.p1': 'หากคุณต้องการจำกัดโฆษณาแบบเฉพาะบุคคลบนอุปกรณ์มือถือของคุณ คุณสามารถปรับการตั้งค่าในโทรศัพท์ของคุณได้:',
            'priv.s4.li1': "<strong>บน Android:</strong> เปิด การตั้งค่า > ความเป็นส่วนตัว > โฆษณา แล้วเลือก 'รีเซ็ตรหัสโฆษณา' หรือ 'ปิดการปรับโฆษณาให้เป็นแบบเฉพาะบุคคล'",
            'priv.s4.li2': '<strong>บน iOS:</strong> ไปที่ การตั้งค่า > ความเป็นส่วนตัว > การติดตาม แล้วปิดตัวเลือกที่อนุญาตให้แอปขอติดตามคุณ',
            'priv.s5.h': '5. ความเป็นส่วนตัวของเด็ก',
            'priv.s5.p1': 'เกมของเราไม่ได้มุ่งเป้าไปที่เด็กอายุต่ำกว่า 13 ปีโดยเจตนา เราไม่เก็บรวบรวมข้อมูลส่วนบุคคลของเด็กโดยเจตนา หากคุณเป็นผู้ปกครองและเชื่อว่าเราได้เก็บรวบรวมข้อมูลโดยไม่ได้รับความยินยอมจากคุณ โปรดติดต่อเราทันที',
            'priv.s6.h': '6. การเปลี่ยนแปลงนโยบายนี้',
            'priv.s6.p1': 'เราขอสงวนสิทธิ์ในการแก้ไขนโยบายความเป็นส่วนตัวนี้ได้ตลอดเวลา การเปลี่ยนแปลงใด ๆ จะถูกเผยแพร่บนหน้านี้พร้อมวันที่อัปเดตที่เกี่ยวข้อง',
            'priv.s7.h': '7. ติดต่อ',
            'priv.s7.p1': 'หากคุณมีคำถามเกี่ยวกับนโยบายความเป็นส่วนตัวนี้หรือการจัดการข้อมูลของคุณ คุณสามารถติดต่อเราได้ทางอีเมล:',
            'terms.title': 'ข้อกำหนดและเงื่อนไขการใช้งาน',
            'terms.updated': 'อัปเดตล่าสุด: 18 มิถุนายน 2026',
            'terms.intro': 'การเข้าถึง ดาวน์โหลด ติดตั้ง หรือใช้วิดีโอเกม เว็บไซต์ เซิร์ฟเวอร์ชุมชน (เช่น Discord) และบริการของ <strong>Titina Games</strong> ถือว่าคุณยอมรับและตกลงที่จะผูกพันตามข้อกำหนดและเงื่อนไขการใช้งานนี้ หากคุณไม่เห็นด้วยกับข้อกำหนดเหล่านี้ โปรดอย่าใช้หรือเข้าถึงบริการของเรา',
            'terms.s1.h': '1. สิทธิ์การใช้งานแบบจำกัด',
            'terms.s1.p1': 'Titina Games มอบสิทธิ์การใช้งานส่วนบุคคล แบบจำกัด ไม่ผูกขาด ไม่สามารถโอนได้ ไม่สามารถให้สิทธิ์ช่วงได้ และเพิกถอนได้ ให้แก่คุณในการดาวน์โหลด ติดตั้ง และใช้เกมและบริการของเรา เพื่อความบันเทิงส่วนตัวและไม่ใช่เชิงพาณิชย์บนอุปกรณ์ที่รองรับซึ่งเป็นของคุณเท่านั้น',
            'terms.s2.h': '2. ทรัพย์สินทางปัญญา',
            'terms.s2.p1': 'สิทธิ์ กรรมสิทธิ์ และผลประโยชน์ทั้งหมดที่เกี่ยวข้องกับเกมและบริการของเรา รวมถึงซอร์สโค้ด กราฟิก การออกแบบ เพลง เอฟเฟกต์เสียง ตัวละคร บทสนทนา ชื่อ โลโก้ และเครื่องหมายการค้า เป็นทรัพย์สินเฉพาะของ Titina Games ห้ามคัดลอก ทำซ้ำ หรือเผยแพร่ทรัพยากรใด ๆ ของเราโดยไม่ได้รับอนุญาตโดยเด็ดขาด',
            'terms.s3.h': '3. ข้อจำกัดและกฎการปฏิบัติ',
            'terms.s3.p1': 'เมื่อใช้บริการของเรา คุณตกลงที่จะไม่กระทำหรือพยายามกระทำการใด ๆ ต่อไปนี้:',
            'terms.s3.li1': 'ดัดแปลง ถอดรหัส ทำวิศวกรรมย้อนกลับ แยกส่วน หรือพยายามดึงซอร์สโค้ดของเกมหรือบริการ',
            'terms.s3.li2': 'ใช้การโกง (cheats) บอท แฮ็ก ม็อด หรือซอฟต์แวร์ของบุคคลที่สามที่ไม่ได้รับอนุญาตเพื่อเปลี่ยนแปลงหรือมีอิทธิพลต่อประสบการณ์การเล่นเกม',
            'terms.s3.li3': 'ใช้ภาษาที่ก้าวร้าว หยาบคาย คุกคาม หรือไม่เหมาะสมในช่องทางชุมชนอย่างเป็นทางการของเรา (เช่น Discord) หรือในระบบตั้งชื่อของเกม',
            'terms.s4.h': '4. บัญชีผู้ใช้และตัวระบุสากล',
            'terms.s4.p1': 'ในการอัปเดตในอนาคต คุณอาจสามารถสร้างบัญชีผู้ใช้หรือใช้ตัวระบุสากลเพื่อบันทึกความคืบหน้าของคุณแบบออนไลน์ คุณเป็นผู้รับผิดชอบแต่เพียงผู้เดียวในการรักษาความปลอดภัยและความลับของข้อมูลรับรองการเข้าสู่ระบบของคุณ Titina Games ไม่รับผิดชอบต่อความสูญเสียใด ๆ ที่เกิดจากการเข้าถึงบัญชีของคุณโดยไม่ได้รับอนุญาต',
            'terms.s5.h': '5. การซื้อในแอปและสกุลเงินเสมือน',
            'terms.s5.p1': 'เกมของเราอาจมีการซื้อในแอปโดยใช้เงินจริงเพื่อรับสกุลเงินเสมือน ไอเทมตกแต่ง หรือไอเทมดิจิทัล ธุรกรรมทั้งหมดจะดำเนินการอย่างปลอดภัยโดยร้านค้าแอปที่เกี่ยวข้อง (เช่น Google Play Store หรือ Apple App Store)',
            'terms.s5.p2': 'ไอเทมและสกุลเงินเสมือนทั้งหมดเป็นสิทธิ์การใช้งานดิจิทัลที่จับต้องไม่ได้ ไม่มีมูลค่าทางการเงินในโลกจริง และไม่สามารถโอนหรือแลกเปลี่ยนเป็นเงินจริงได้ เว้นแต่กฎหมายท้องถิ่นหรือนโยบายของร้านค้าแอปจะกำหนดไว้เป็นอย่างอื่น การซื้อทั้งหมดถือเป็นที่สิ้นสุดและไม่สามารถขอคืนเงินได้',
            'terms.s6.h': '6. โฆษณาและบริการของบุคคลที่สาม',
            'terms.s6.p1': 'เกมฟรีของเราอาจมีโฆษณาแบบรวมที่จัดการผ่าน Google AdMob หรือแพลตฟอร์มอื่นที่คล้ายกัน โฆษณาเหล่านี้อาจโต้ตอบกับอุปกรณ์ของคุณตามที่ระบุไว้ในนโยบายความเป็นส่วนตัวของเรา Titina Games ไม่รับรองและไม่รับผิดชอบต่อเนื้อหา ผลิตภัณฑ์ หรือบริการที่นำเสนอโดยผู้โฆษณาภายนอก',
            'terms.s7.h': '7. การจำกัดความรับผิด',
            'terms.s7.p1': "เกมและบริการของเราจัดหาให้ 'ตามสภาพที่เป็นอยู่' และ 'ตามที่มีให้บริการ' ในโหมดเล่นแบบออฟไลน์ ความคืบหน้าของคุณจะถูกจัดเก็บไว้ในอุปกรณ์ของคุณ Titina Games ไม่รับผิดชอบต่อการสูญเสียความคืบหน้า ข้อมูล หรือการซื้อ หากคุณถอนการติดตั้งแอป ล้างแคช ฟอร์แมตอุปกรณ์ หรือหากอุปกรณ์ของคุณเกิดความล้มเหลวของฮาร์ดแวร์",
            'terms.s8.h': '8. การสนับสนุนทางเทคนิคและการติดต่อ',
            'terms.s8.p1': 'สำหรับข้อสอบถามทางกฎหมาย รายงานข้อผิดพลาด ความคิดเห็น หรือคำขอการสนับสนุนทางเทคนิค คุณสามารถเขียนถึงเราได้โดยตรงที่อีเมลฝ่ายบริการลูกค้าอย่างเป็นทางการของเรา:'
        },

        /* ================= မြန်မာ (Burmese) ================= */
        my: {
            'priv.title': 'ကိုယ်ရေးအချက်အလက် မူဝါဒ',
            'priv.updated': 'နောက်ဆုံးအပ်ဒိတ်: ၂၀၂၆ ခုနှစ်၊ ဇွန်လ ၈ ရက်',
            'priv.intro': 'Titina Games တွင် ကျွန်ုပ်တို့သည် သင့်ကိုယ်ရေးအချက်အလက်ကို တန်ဖိုးထားပါသည်။ ဤကိုယ်ရေးအချက်အလက်မူဝါဒသည် ကျွန်ုပ်တို့၏ မိုဘိုင်းဂိမ်းများနှင့် ဆက်စပ်ဝန်ဆောင်မှုများကို သင်အသုံးပြုသည့်အခါ အချက်အလက်များကို မည်သို့ စုဆောင်း၊ အသုံးပြုနှင့် ထုတ်ဖော်သည်ကို ရှင်းပြပါသည်။',
            'priv.s1.h': '၁။ အချက်အလက် စုဆောင်းခြင်း',
            'priv.s1.p1': 'ကျွန်ုပ်တို့၏ အက်ပ်များသည် အသုံးပြုသူများထံမှ ကိုယ်ရေးကိုယ်တာ ခွဲခြားသိရှိနိုင်သော အချက်အလက်များကို တိုက်ရိုက် မစုဆောင်းရန် ဒီဇိုင်းထုတ်ထားပါသည်။ ဂိမ်းကစားရန်အတွက် အကောင့်မှတ်ပုံတင်ခြင်း၊ အမည်၊ အီးမေးလ် သို့မဟုတ် ဖုန်းနံပါတ်များ တောင်းဆိုခြင်း မရှိပါ။',
            'priv.s1.p2': 'သို့သော် ကျွန်ုပ်တို့၏ ဝန်ဆောင်မှုများကို အခမဲ့ ဆက်လက်ထားရှိနိုင်ရန်နှင့် ဝင်ငွေရရှိစေရန်အတွက် နည်းပညာဆိုင်ရာ အချက်အလက်များကို အလိုအလျောက် စုဆောင်းသည့် ပြင်ပ (third-party) ကိရိယာများကို ပေါင်းစပ်အသုံးပြုပါသည်။',
            'priv.s2.h': '၂။ ပြင်ပဝန်ဆောင်မှုများ (ကြော်ငြာနှင့် ဝင်ငွေရှာဖွေခြင်း)',
            'priv.s2.p1': 'ကျွန်ုပ်တို့၏ ဂိမ်းများသည် ကြော်ငြာများပြသရန် Google AdMob ကို အသုံးပြုနိုင်ပါသည်။ AdMob သည် သင့်အကြောင်း အချက်အလက်များကို အလိုအလျောက် စုဆောင်းပြီး လုပ်ဆောင်နိုင်ပါသည်။ ဤအချက်အလက်များတွင် အောက်ပါတို့ ပါဝင်သည်—',
            'priv.s2.li1': 'စက်ပစ္စည်း၏ သီးသန့်ကြော်ငြာ ခွဲခြားသတ်မှတ်မှုများ (Google ကြော်ငြာ ID သို့မဟုတ် Apple ၏ IDFA ကဲ့သို့)။',
            'priv.s2.li2': 'စက်ပစ္စည်းအကြောင်း အချက်အလက် (ထုတ်လုပ်သူ၊ မော်ဒယ်၊ လည်ပတ်မှုစနစ်၊ ဘာသာစကားနှင့် ဖန်သားပြင် ကြည်လင်ပြတ်သားမှု)။',
            'priv.s2.li3': 'ကြော်ငြာများနှင့် အပြန်အလှန်တုံ့ပြန်မှု အချက်အလက် (နှိပ်မှုများ၊ ပြသမှုများနှင့် ကြည့်ရှုမှုများ)။',
            'priv.s2.li4': 'စနစ်ရောဂါရှာဖွေမှု အချက်အလက် (ချွတ်ယွင်းချက် အစီရင်ခံစာများ (crash logs)၊ အက်ပ်စွမ်းဆောင်ရည်နှင့် မှတ်ဉာဏ်အသုံးပြုမှု)။',
            'priv.s2.li5': 'IP လိပ်စာမှ ရရှိသော ခန့်မှန်းတည်နေရာ (မြို့ သို့မဟုတ် နိုင်ငံ အဆင့်)။',
            'priv.s2.p2': 'ကြော်ငြာနှင့် ဆက်စပ်သော Google ၏ ကိုယ်ရေးအချက်အလက် မူဝါဒကို အောက်ပါ လင့်ခ်တွင် ကြည့်ရှုနိုင်ပါသည်— Google ၏ ကြော်ငြာ မူဝါဒနှင့် အခြေခံမူများ။',
            'priv.s3.h': '၃။ အချက်အလက် အသုံးပြုခြင်း',
            'priv.s3.p1': 'အလိုအလျောက် စုဆောင်းထားသော နည်းပညာဆိုင်ရာ အချက်အလက်များကို အောက်ပါအတွက်သာ အသုံးပြုပါသည်—',
            'priv.s3.li1': 'သင့်ဆက်တင်များက ခွင့်ပြုသည့်အတိုင်း သင့်တော်သလို ကိုယ်ပိုင်သတ်မှတ်ထားသော သို့မဟုတ် ကိုယ်ပိုင်မသတ်မှတ်ထားသော ကြော်ငြာများ ပြသရန်။',
            'priv.s3.li2': 'ကြော်ငြာစနစ်အတွင်း လိမ်လည်မှုနှင့် အန္တရာယ်ရှိသော လုပ်ဆောင်ချက်များကို ကာကွယ်ရန်။',
            'priv.s3.li3': 'ကြော်ငြာ ကမ်ပိန်းများ၏ စွမ်းဆောင်ရည်ကို ခွဲခြမ်းစိတ်ဖြာရန်။',
            'priv.s3.li4': 'နည်းပညာဆိုင်ရာ ပြဿနာများကို ရှာဖွေဖော်ထုတ်ရန်၊ စနစ်ချွတ်ယွင်းချက်များကို ပြင်ဆင်ရန်နှင့် ကစားမှုအတွေ့အကြုံကို ပိုမိုကောင်းမွန်စေရန်။',
            'priv.s4.h': '၄။ အသုံးပြုသူ၏ ကိုယ်ရေးအချက်အလက် ရွေးချယ်စရာများ',
            'priv.s4.p1': 'သင့်မိုဘိုင်းစက်ပစ္စည်းတွင် ကိုယ်ပိုင်သတ်မှတ်ကြော်ငြာများကို ကန့်သတ်လိုပါက သင့်ဖုန်းရှိ ဆက်တင်များကို ချိန်ညှိနိုင်ပါသည်—',
            'priv.s4.li1': "<strong>Android တွင်—</strong> ဆက်တင်များ > ကိုယ်ရေးအချက်အလက် > ကြော်ငြာများ ကိုဖွင့်ပြီး 'ကြော်ငြာ ID ကို ပြန်လည်သတ်မှတ်ရန်' သို့မဟုတ် 'ကြော်ငြာ ကိုယ်ပိုင်သတ်မှတ်ခြင်းကို ပိတ်ရန်' ကို ရွေးချယ်ပါ။",
            'priv.s4.li2': '<strong>iOS တွင်—</strong> ဆက်တင်များ > ကိုယ်ရေးအချက်အလက် > ခြေရာခံခြင်း သို့သွားပြီး အက်ပ်များက သင့်ကို ခြေရာခံရန် တောင်းဆိုခွင့်ကို ပိတ်ပါ။',
            'priv.s5.h': '၅။ ကလေးများ၏ ကိုယ်ရေးအချက်အလက်',
            'priv.s5.p1': 'ကျွန်ုပ်တို့၏ ဂိမ်းများသည် အသက် ၁၃ နှစ်အောက် ကလေးများအတွက် ရည်ရွယ်၍ ပြုလုပ်ထားခြင်း မဟုတ်ပါ။ ကျွန်ုပ်တို့သည် ကလေးများ၏ ကိုယ်ရေးအချက်အလက်ကို သိလျက်နှင့် မစုဆောင်းပါ။ သင်သည် မိဘ သို့မဟုတ် အုပ်ထိန်းသူဖြစ်ပြီး သင့်သဘောတူညီချက်မရှိဘဲ ကျွန်ုပ်တို့ အချက်အလက်စုဆောင်းခဲ့သည်ဟု ယုံကြည်ပါက ကျွန်ုပ်တို့ထံ ချက်ချင်း ဆက်သွယ်ပါ။',
            'priv.s6.h': '၆။ ဤမူဝါဒ၏ ပြောင်းလဲမှုများ',
            'priv.s6.p1': 'ဤကိုယ်ရေးအချက်အလက် မူဝါဒကို အချိန်မရွေး ပြင်ဆင်ခွင့်ကို ကျွန်ုပ်တို့ ထိန်းသိမ်းထားပါသည်။ ပြောင်းလဲမှုများကို သက်ဆိုင်ရာ အပ်ဒိတ်ရက်စွဲနှင့်အတူ ဤစာမျက်နှာတွင် ဖော်ပြပါမည်။',
            'priv.s7.h': '၇။ ဆက်သွယ်ရန်',
            'priv.s7.p1': 'ဤကိုယ်ရေးအချက်အလက် မူဝါဒ သို့မဟုတ် သင့်အချက်အလက် ကိုင်တွယ်မှုနှင့် ပတ်သက်၍ မေးခွန်းရှိပါက အီးမေးလ်မှတစ်ဆင့် ကျွန်ုပ်တို့ကို ဆက်သွယ်နိုင်ပါသည်—',
            'terms.title': 'အသုံးပြုမှု စည်းမျဉ်းနှင့် သတ်မှတ်ချက်များ',
            'terms.updated': 'နောက်ဆုံးအပ်ဒိတ်: ၂၀၂၆ ခုနှစ်၊ ဇွန်လ ၁၈ ရက်',
            'terms.intro': '<strong>Titina Games</strong> ၏ ဗီဒီယိုဂိမ်းများ၊ ဝဘ်ဆိုက်များ၊ အသိုင်းအဝိုင်း ဆာဗာများ (Discord ကဲ့သို့) နှင့် ဝန်ဆောင်မှုများကို ဝင်ရောက်ခြင်း၊ ဒေါင်းလုဒ်လုပ်ခြင်း၊ ထည့်သွင်းခြင်း သို့မဟုတ် အသုံးပြုခြင်းဖြင့် သင်သည် ဤအသုံးပြုမှု စည်းမျဉ်းနှင့် သတ်မှတ်ချက်များကို လိုက်နာရန် သဘောတူသည်။ ဤစည်းမျဉ်းများကို သဘောမတူပါက ကျွန်ုပ်တို့၏ ဝန်ဆောင်မှုများကို အသုံးမပြုပါနှင့်။',
            'terms.s1.h': '၁။ ကန့်သတ်လိုင်စင်',
            'terms.s1.p1': 'Titina Games သည် ကျွန်ုပ်တို့၏ ဂိမ်းများနှင့် ဝန်ဆောင်မှုများကို သင်ပိုင်ဆိုင်သော သင့်လျော်သည့် စက်ပစ္စည်းများပေါ်တွင် ကိုယ်ရေးကိုယ်တာ၊ စီးပွားရေးမဟုတ်သော ဖျော်ဖြေမှုအတွက်သာ ဒေါင်းလုဒ်လုပ်ခြင်း၊ ထည့်သွင်းခြင်းနှင့် အသုံးပြုခြင်းအတွက် ကိုယ်ရေးကိုယ်တာ၊ ကန့်သတ်ထားသော၊ သီးသန့်မဟုတ်သော၊ လွှဲပြောင်း၍မရသော၊ ထပ်ဆင့်လိုင်စင်ပေး၍မရသော နှင့် ရုပ်သိမ်းနိုင်သော လိုင်စင်တစ်ခုကို သင့်အား ပေးအပ်ပါသည်။',
            'terms.s2.h': '၂။ ဉာဏပစ္စည်း ပိုင်ဆိုင်မှု',
            'terms.s2.p1': 'ကျွန်ုပ်တို့၏ ဂိမ်းများနှင့် ဝန်ဆောင်မှုများနှင့် ဆက်စပ်သော အခွင့်အရေး၊ ပိုင်ဆိုင်မှုနှင့် အကျိုးစီးပွားအားလုံး— source code၊ ဂရပ်ဖစ်များ၊ ဒီဇိုင်းများ၊ ဂီတ၊ အသံအထူးပြုလုပ်ချက်များ၊ ဇာတ်ကောင်များ၊ စကားပြောများ၊ အမည်များ၊ လိုဂိုများနှင့် ကုန်အမှတ်တံဆိပ်များ အပါအဝင်— သည် Titina Games ၏ သီးသန့်ပိုင်ဆိုင်မှုဖြစ်သည်။ ကျွန်ုပ်တို့၏ အရင်းအမြစ်များကို ခွင့်ပြုချက်မရှိဘဲ ကူးယူခြင်း၊ ပွားခြင်း သို့မဟုတ် ဖြန့်ဝေခြင်းကို တင်းကြပ်စွာ တားမြစ်ထားသည်။',
            'terms.s3.h': '၃။ ကန့်သတ်ချက်များနှင့် ကျင့်ဝတ်စည်းကမ်း',
            'terms.s3.p1': 'ကျွန်ုပ်တို့၏ ဝန်ဆောင်မှုများကို အသုံးပြုသည့်အခါ အောက်ပါ လုပ်ဆောင်ချက်များကို ပြုလုပ်ရန် သို့မဟုတ် ကြိုးပမ်းရန် မပြုလုပ်ရန် သင်သဘောတူသည်—',
            'terms.s3.li1': 'ဂိမ်းများ သို့မဟုတ် ဝန်ဆောင်မှုများ၏ source code ကို ပြုပြင်ခြင်း၊ decompile လုပ်ခြင်း၊ reverse engineer လုပ်ခြင်း၊ ဖြုတ်ခြင်း သို့မဟုတ် ထုတ်ယူရန် ကြိုးပမ်းခြင်း။',
            'terms.s3.li2': 'ကစားမှုအတွေ့အကြုံကို ပြောင်းလဲ သို့မဟုတ် လွှမ်းမိုးရန် လိမ်လည်မှုများ (cheats)၊ bot များ၊ hack များ၊ mod များ သို့မဟုတ် ခွင့်ပြုချက်မရှိသော ပြင်ပ ဆော့ဖ်ဝဲများကို အသုံးပြုခြင်း။',
            'terms.s3.li3': 'ကျွန်ုပ်တို့၏ တရားဝင် အသိုင်းအဝိုင်း ချန်နယ်များ (Discord ကဲ့သို့) သို့မဟုတ် ဂိမ်း၏ အမည်ပေးစနစ်များတွင် ထိခိုက်စေသော၊ ကြမ်းတမ်းသော၊ နှောင့်ယှက်သော သို့မဟုတ် မသင့်လျော်သော ဘာသာစကားကို အသုံးပြုခြင်း။',
            'terms.s4.h': '၄။ အသုံးပြုသူ အကောင့်များနှင့် Global Identifier',
            'terms.s4.p1': 'အနာဂတ် အပ်ဒိတ်များတွင် သင့်တိုးတက်မှုကို အွန်လိုင်းတွင် သိမ်းဆည်းရန် အသုံးပြုသူအကောင့်တစ်ခု ဖန်တီးခြင်း သို့မဟုတ် global identifier တစ်ခု အသုံးပြုနိုင်ဖွယ်ရှိသည်။ သင့် login အထောက်အထားများ၏ လုံခြုံမှုနှင့် လျှို့ဝှက်မှုကို ထိန်းသိမ်းရန် သင်တစ်ဦးတည်း တာဝန်ရှိသည်။ သင့်အကောင့်ကို ခွင့်ပြုချက်မရှိဘဲ ဝင်ရောက်ခြင်းကြောင့် ဖြစ်ပေါ်လာသော ဆုံးရှုံးမှုအတွက် Titina Games တာဝန်မယူပါ။',
            'terms.s5.h': '၅။ အက်ပ်တွင်း ဝယ်ယူမှုများနှင့် Virtual ငွေကြေး',
            'terms.s5.p1': 'ကျွန်ုပ်တို့၏ ဂိမ်းများတွင် virtual ငွေကြေး၊ အလှဆင်ပစ္စည်းများ သို့မဟုတ် ဒစ်ဂျစ်တယ် ပစ္စည်းများ ရယူရန် ငွေအစစ်ဖြင့် အက်ပ်တွင်း ဝယ်ယူမှုများ ပါဝင်နိုင်သည်။ ငွေပေးငွေယူ အားလုံးကို သက်ဆိုင်ရာ app store (Google Play Store သို့မဟုတ် Apple App Store ကဲ့သို့) မှ လုံခြုံစွာ လုပ်ဆောင်ပါသည်။',
            'terms.s5.p2': 'virtual ပစ္စည်းများနှင့် ငွေကြေးအားလုံးသည် ကိုင်တွယ်၍မရသော ဒစ်ဂျစ်တယ် လိုင်စင်များဖြစ်ပြီး တကယ့်ကမ္ဘာတွင် ငွေကြေးတန်ဖိုးမရှိပါ၊ ငွေအစစ်ဖြင့် လွှဲပြောင်း သို့မဟုတ် လဲလှယ်၍ မရပါ။ ဒေသဆိုင်ရာ ဥပဒေ သို့မဟုတ် app store မူဝါဒများက သတ်မှတ်ထားခြင်းမှလွဲ၍ ဝယ်ယူမှုအားလုံးသည် အပြီးအပြတ်ဖြစ်ပြီး ငွေပြန်အမ်း၍ မရပါ။',
            'terms.s6.h': '၆။ ကြော်ငြာနှင့် ပြင်ပဝန်ဆောင်မှုများ',
            'terms.s6.p1': 'ကျွန်ုပ်တို့၏ အခမဲ့ ဂိမ်းများတွင် Google AdMob သို့မဟုတ် အလားတူ ပလက်ဖောင်းများမှတစ်ဆင့် စီမံခန့်ခွဲသော ပေါင်းစပ်ကြော်ငြာများ ပါဝင်နိုင်သည်။ ဤကြော်ငြာများသည် ကျွန်ုပ်တို့၏ ကိုယ်ရေးအချက်အလက် မူဝါဒတွင် ဖော်ပြထားသည့်အတိုင်း သင့်စက်ပစ္စည်းနှင့် အပြန်အလှန် ဆက်သွယ်နိုင်သည်။ ပြင်ပ ကြော်ငြာရှင်များက ကမ်းလှမ်းသော အကြောင်းအရာ၊ ကုန်ပစ္စည်း သို့မဟုတ် ဝန်ဆောင်မှုများအတွက် Titina Games က ထောက်ခံခြင်းမရှိသကဲ့သို့ တာဝန်လည်း မယူပါ။',
            'terms.s7.h': '၇။ တာဝန်ကန့်သတ်ချက်',
            'terms.s7.p1': "ကျွန်ုပ်တို့၏ ဂိမ်းများနှင့် ဝန်ဆောင်မှုများကို 'ရှိသည့်အတိုင်း' နှင့် 'ရရှိနိုင်သည့်အတိုင်း' ပံ့ပိုးပေးပါသည်။ အော့ဖ်လိုင်း ကစားမှုများတွင် သင့်တိုးတက်မှုကို သင့်စက်ပစ္စည်းတွင် ဒေသတွင်း သိမ်းဆည်းသည်။ သင်သည် အက်ပ်ကို ဖြုတ်ခြင်း၊ cache ကို ရှင်းလင်းခြင်း၊ စက်ပစ္စည်းကို ဖော်မတ်လုပ်ခြင်း သို့မဟုတ် သင့်စက်ပစ္စည်း ဟာ့ဒ်ဝဲ ချွတ်ယွင်းမှုဖြစ်ပါက တိုးတက်မှု၊ ဒေတာ သို့မဟုတ် ဝယ်ယူမှုများ ဆုံးရှုံးခြင်းအတွက် Titina Games တာဝန်မယူပါ။",
            'terms.s8.h': '၈။ နည်းပညာ အကူအညီနှင့် ဆက်သွယ်ရန်',
            'terms.s8.p1': 'ဥပဒေဆိုင်ရာ မေးမြန်းချက်များ၊ ချွတ်ယွင်းချက် အစီရင်ခံစာများ၊ အကြံပြုချက်များ သို့မဟုတ် နည်းပညာ အကူအညီ တောင်းဆိုမှုများအတွက် ကျွန်ုပ်တို့၏ တရားဝင် customer service အီးမေးလ်သို့ တိုက်ရိုက် ရေးသားနိုင်ပါသည်—'
        },

        /* ================= हिन्दी (Hindi) ================= */
        hi: {
            'priv.title': 'गोपनीयता नीति',
            'priv.updated': 'अंतिम अपडेट: 8 जून 2026',
            'priv.intro': 'Titina Games में, हम आपकी गोपनीयता को महत्व देते हैं। यह गोपनीयता नीति बताती है कि जब आप हमारे मोबाइल गेम और किसी भी अन्य संबंधित सेवा का उपयोग करते हैं, तो जानकारी कैसे एकत्र, उपयोग और साझा की जाती है।',
            'priv.s1.h': '1. जानकारी का संग्रह',
            'priv.s1.p1': 'हमारे एप्लिकेशन इस तरह बनाए गए हैं कि वे उपयोगकर्ताओं से सीधे व्यक्तिगत पहचान योग्य जानकारी एकत्र न करें। खेलने के लिए हम खाता पंजीकरण, नाम, ईमेल या फ़ोन नंबर नहीं माँगते।',
            'priv.s1.p2': 'हालाँकि, अपनी सेवाओं को मुफ़्त बनाए रखने और उनसे आय अर्जित करने के लिए, हम तृतीय-पक्ष टूल को एकीकृत करते हैं जो स्वचालित रूप से तकनीकी जानकारी एकत्र करते हैं।',
            'priv.s2.h': '2. तृतीय-पक्ष सेवाएँ (विज्ञापन और मुद्रीकरण)',
            'priv.s2.p1': 'हमारे गेम विज्ञापन दिखाने के लिए Google AdMob का उपयोग कर सकते हैं। AdMob आपके बारे में जानकारी स्वचालित रूप से एकत्र और संसाधित कर सकता है। इस जानकारी में, अन्य बातों के अलावा, शामिल हैं:',
            'priv.s2.li1': 'डिवाइस के अद्वितीय विज्ञापन पहचानकर्ता (जैसे Google विज्ञापन ID या Apple का IDFA)।',
            'priv.s2.li2': 'डिवाइस के बारे में डेटा (निर्माता, मॉडल, ऑपरेटिंग सिस्टम, भाषा और स्क्रीन रिज़ॉल्यूशन)।',
            'priv.s2.li3': 'विज्ञापनों के साथ इंटरैक्शन का डेटा (क्लिक, इंप्रेशन और व्यू)।',
            'priv.s2.li4': 'सिस्टम डायग्नोस्टिक जानकारी (क्रैश रिपोर्ट या क्रैश लॉग, ऐप का प्रदर्शन और मेमोरी उपयोग)।',
            'priv.s2.li5': 'IP पते से प्राप्त अनुमानित स्थान (शहर या देश स्तर पर)।',
            'priv.s2.p2': 'आप विज्ञापन से संबंधित Google की गोपनीयता नीति निम्नलिखित लिंक पर देख सकते हैं: Google की विज्ञापन नीतियाँ और सिद्धांत।',
            'priv.s3.h': '3. जानकारी का उपयोग',
            'priv.s3.p1': 'स्वचालित रूप से एकत्र की गई तकनीकी जानकारी का उपयोग केवल निम्नलिखित के लिए किया जाता है:',
            'priv.s3.li1': 'आपकी सेटिंग्स के अनुसार और जहाँ उपयुक्त हो, वैयक्तिकृत या गैर-वैयक्तिकृत विज्ञापन दिखाना।',
            'priv.s3.li2': 'विज्ञापन प्रणाली के भीतर धोखाधड़ी और दुर्भावनापूर्ण गतिविधियों को रोकना।',
            'priv.s3.li3': 'विज्ञापन अभियानों के प्रदर्शन का विश्लेषण करना।',
            'priv.s3.li4': 'तकनीकी समस्याओं का निदान करना, सिस्टम त्रुटियों को ठीक करना और गेमिंग अनुभव को बेहतर बनाना।',
            'priv.s4.h': '4. उपयोगकर्ता के गोपनीयता विकल्प',
            'priv.s4.p1': 'यदि आप अपने मोबाइल डिवाइस पर वैयक्तिकृत विज्ञापन सीमित करना चाहते हैं, तो आप अपने फ़ोन की सेटिंग्स समायोजित कर सकते हैं:',
            'priv.s4.li1': "<strong>Android पर:</strong> सेटिंग्स > गोपनीयता > विज्ञापन खोलें और 'विज्ञापन ID रीसेट करें' या 'विज्ञापन वैयक्तिकरण बंद करें' चुनें।",
            'priv.s4.li2': '<strong>iOS पर:</strong> सेटिंग्स > गोपनीयता > ट्रैकिंग पर जाएँ और ऐप्स को आपको ट्रैक करने का अनुरोध करने की अनुमति देने वाले विकल्प को बंद कर दें।',
            'priv.s5.h': '5. बच्चों की गोपनीयता',
            'priv.s5.p1': 'हमारे गेम जानबूझकर 13 वर्ष से कम उम्र के बच्चों के लिए नहीं बनाए गए हैं। हम जानबूझकर बच्चों से व्यक्तिगत जानकारी एकत्र नहीं करते। यदि आप माता-पिता या अभिभावक हैं और मानते हैं कि हमने आपकी सहमति के बिना जानकारी एकत्र की है, तो कृपया तुरंत हमसे संपर्क करें।',
            'priv.s6.h': '6. इस नीति में बदलाव',
            'priv.s6.p1': 'हम इस गोपनीयता नीति को किसी भी समय संशोधित करने का अधिकार सुरक्षित रखते हैं। कोई भी बदलाव संबंधित अपडेट तिथि के साथ इस पृष्ठ पर प्रकाशित किया जाएगा।',
            'priv.s7.h': '7. संपर्क',
            'priv.s7.p1': 'यदि इस गोपनीयता नीति या आपके डेटा के प्रबंधन के बारे में आपके कोई प्रश्न हैं, तो आप ईमेल के माध्यम से हमसे संपर्क कर सकते हैं:',
            'terms.title': 'उपयोग के नियम और शर्तें',
            'terms.updated': 'अंतिम अपडेट: 18 जून 2026',
            'terms.intro': '<strong>Titina Games</strong> के वीडियो गेम, वेबसाइटों, कम्युनिटी सर्वर (जैसे Discord) और सेवाओं तक पहुँचकर, उन्हें डाउनलोड, इंस्टॉल या उपयोग करके, आप इन उपयोग के नियमों और शर्तों का पालन करने और इनसे बंधे रहने के लिए सहमत होते हैं। यदि आप इन शर्तों से सहमत नहीं हैं, तो कृपया हमारी सेवाओं का उपयोग या उन तक पहुँच न करें।',
            'terms.s1.h': '1. सीमित लाइसेंस',
            'terms.s1.p1': 'Titina Games आपको हमारे गेम और सेवाओं को डाउनलोड, इंस्टॉल और उपयोग करने के लिए एक व्यक्तिगत, सीमित, गैर-अनन्य, गैर-हस्तांतरणीय, गैर-उप-लाइसेंस योग्य और निरस्त करने योग्य लाइसेंस प्रदान करता है, जो केवल आपके स्वामित्व वाले संगत डिवाइस पर आपके व्यक्तिगत, गैर-व्यावसायिक मनोरंजन के लिए है।',
            'terms.s2.h': '2. बौद्धिक संपदा',
            'terms.s2.p1': 'हमारे गेम और सेवाओं से संबंधित सभी अधिकार, स्वामित्व और हित, जिनमें सोर्स कोड, ग्राफ़िक्स, डिज़ाइन, संगीत, ध्वनि प्रभाव, पात्र, संवाद, नाम, लोगो और ट्रेडमार्क शामिल हैं, Titina Games की अनन्य संपत्ति हैं। हमारे किसी भी संसाधन की अनधिकृत प्रतिलिपि, पुनरुत्पादन या वितरण सख्त वर्जित है।',
            'terms.s3.h': '3. प्रतिबंध और आचार संहिता',
            'terms.s3.p1': 'हमारी सेवाओं का उपयोग करते समय, आप निम्नलिखित में से कोई भी कार्य न करने और न करने का प्रयास करने के लिए सहमत होते हैं:',
            'terms.s3.li1': 'गेम या सेवाओं के सोर्स कोड को संशोधित करना, डीकंपाइल करना, रिवर्स इंजीनियर करना, अलग करना या निकालने का प्रयास करना।',
            'terms.s3.li2': 'गेमिंग अनुभव को बदलने या प्रभावित करने के लिए चीट, बॉट, हैक, मॉड या किसी भी अनधिकृत तृतीय-पक्ष सॉफ़्टवेयर का उपयोग करना।',
            'terms.s3.li3': 'हमारे आधिकारिक कम्युनिटी चैनलों (जैसे Discord) में या गेम की नामकरण प्रणाली में आपत्तिजनक, अपमानजनक, उत्पीड़नकारी या अनुचित भाषा का उपयोग करना।',
            'terms.s4.h': '4. उपयोगकर्ता खाते और ग्लोबल पहचानकर्ता',
            'terms.s4.p1': 'भविष्य के अपडेट में, आप अपनी प्रगति को ऑनलाइन सहेजने के लिए एक उपयोगकर्ता खाता बना सकते हैं या एक ग्लोबल पहचानकर्ता का उपयोग कर सकते हैं। अपने लॉगिन क्रेडेंशियल की सुरक्षा और गोपनीयता बनाए रखने के लिए आप पूरी तरह ज़िम्मेदार हैं। आपके खाते तक अनधिकृत पहुँच से होने वाले किसी भी नुकसान के लिए Titina Games ज़िम्मेदार नहीं है।',
            'terms.s5.h': '5. ऐप के भीतर खरीदारी और वर्चुअल मुद्रा',
            'terms.s5.p1': 'हमारे गेम में वर्चुअल मुद्रा, कॉस्मेटिक या डिजिटल आइटम प्राप्त करने के लिए वास्तविक पैसे का उपयोग करके ऐप के भीतर खरीदारी शामिल हो सकती है। सभी लेनदेन संबंधित ऐप स्टोर (जैसे Google Play Store या Apple App Store) द्वारा सुरक्षित रूप से संसाधित किए जाते हैं।',
            'terms.s5.p2': 'सभी वर्चुअल आइटम और मुद्राएँ अमूर्त डिजिटल लाइसेंस हैं, वास्तविक दुनिया में इनका कोई मौद्रिक मूल्य नहीं है और ये वास्तविक पैसे के लिए हस्तांतरणीय या विनिमय योग्य नहीं हैं। जब तक स्थानीय कानून या ऐप स्टोर की नीतियों द्वारा आवश्यक न हो, सभी खरीदारी अंतिम और गैर-वापसी योग्य हैं।',
            'terms.s6.h': '6. विज्ञापन और तृतीय-पक्ष सेवाएँ',
            'terms.s6.p1': 'हमारे मुफ़्त गेम में Google AdMob या अन्य समान प्लेटफ़ॉर्म के माध्यम से प्रबंधित एकीकृत विज्ञापन हो सकते हैं। ये विज्ञापन हमारी गोपनीयता नीति में बताए अनुसार आपके डिवाइस के साथ इंटरैक्ट कर सकते हैं। Titina Games बाहरी विज्ञापनदाताओं द्वारा प्रस्तुत सामग्री, उत्पादों या सेवाओं का समर्थन नहीं करता और उनके लिए ज़िम्मेदार नहीं है।',
            'terms.s7.h': '7. दायित्व की सीमा',
            'terms.s7.p1': "हमारे गेम और सेवाएँ 'जैसी हैं' और 'जैसी उपलब्ध हैं' के आधार पर प्रदान की जाती हैं। ऑफ़लाइन गेम मोड में, आपकी प्रगति आपके डिवाइस पर स्थानीय रूप से संग्रहीत होती है। यदि आप ऐप को अनइंस्टॉल करते हैं, कैश साफ़ करते हैं, अपने डिवाइस को फ़ॉर्मेट करते हैं या यदि आपके डिवाइस में हार्डवेयर विफलता होती है, तो प्रगति, डेटा या खरीदारी के नुकसान के लिए Titina Games ज़िम्मेदार नहीं है।",
            'terms.s8.h': '8. तकनीकी सहायता और संपर्क',
            'terms.s8.p1': 'कानूनी पूछताछ, बग रिपोर्ट, प्रतिक्रिया या तकनीकी सहायता अनुरोधों के लिए, आप सीधे हमारे आधिकारिक ग्राहक सेवा ईमेल पर लिख सकते हैं:'
        }
    };

    Object.keys(legal).forEach(function (code) {
        if (translations[code]) {
            for (var k in legal[code]) {
                if (Object.prototype.hasOwnProperty.call(legal[code], k)) {
                    translations[code][k] = legal[code][k];
                }
            }
        }
    });

    // If the switcher already built its menu (i18n init ran first),
    // re-apply the SAVED language so the merged legal keys take effect.
    if (document.querySelector('.lang-option')) {
        var saved = null;
        try { saved = localStorage.getItem('titina_lang'); } catch (e) { /* ignore */ }
        if (saved && translations[saved] && typeof applyLanguage === 'function') {
            applyLanguage(saved);
        }
    }
})();
